Add exit on error

diff --git a/tools-scripts-helper b/tools-scripts-helper
--- a/tools-scripts-helper
+++ b/tools-scripts-helper
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+# Exit immediately if any command exits with a non-zero status
+set -e
+
 # Check if the script is executed with root privileges
 if [ "$(id -u)" != "0" ]; then
     echo "This script must be run with root privileges. Please use 'sudo' to execute it."
